# -*- coding: utf-8 -*-
"""real_world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EzKZzswC9bV7t4n5z8-Nj_Fdgjdjckkp
"""

!pip install ultralytics -q

from ultralytics import YOLO
from google.colab import files
from IPython.display import Image, display
import os

!pip uninstall -y pillow supervision
!pip install inference-sdk

from inference_sdk import InferenceHTTPClient

CLIENT = InferenceHTTPClient(
    api_url="https://serverless.roboflow.com",
    api_key="4NrXnUVGSjihF90jNjJ4"
)

result = CLIENT.infer("YOUR_IMAGE.jpg", model_id="helmet-detection-xibyl/2")

from roboflow import Roboflow

rf = Roboflow(api_key="4NrXnUVGSjihF90jNjJ4")

workspace = rf.workspace("priyanshus-workspace-ph4rz")
project = workspace.project("helmet")

dataset = project.version(1).download("yolov8")

!ls -lh

!file *



!file helmet.zip

!ls -R helmet-1

!ls /content/helmet-1

!ls -lh

!unzip roboflow.zip -d helmet-1

from ultralytics import YOLO

model = YOLO("yolov8n.pt")
model.train(data="/content/helmet-1/data.yaml", epochs=50)